import asyncio


# noinspection SpellCheckingInspection
async def start_turf_cm_amiibos(ctx):
    turf_battle = await ctx.send("Ay! (Turf War Begin!)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You ink base..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (Opponent goes straight for the middle..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You get to the middle..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You clash at each others heads..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay! (**Callie & Marie** sends you a special modified weapon!)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You save this weapon and use it at the best time possible in the battle..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (The timer is closer to running out..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (10..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (9..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (8..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (7..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (6..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (5..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (4..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (3..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (2..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (1..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay! (Results coming in..!)")
    await asyncio.sleep(1.5)


# noinspection SpellCheckingInspection
async def start_turf_extreme_cm_amiibos(ctx):
    turf_battle = await ctx.send("Ay! (Extreme Turf War Begin!)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You go straight for the middle..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (Opponent goes straight for the middle..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You both clash at each others heads..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You've been splatted 49 times..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (They've been splatted 49 times..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay! (**Callie & Marie** sends you a special modified weapon!)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You save this weapon and use it at the best time possible in the battle..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (The final splat before time goes out will determine the winner..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (6..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (5..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (4..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (3..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (2..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (1..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay! (Results coming in..!)")
    await asyncio.sleep(2.5)


# noinspection SpellCheckingInspection
async def start_blitz_pm_amiibos(ctx):
    turf_battle = await ctx.send("Ay! (Experience Blitz Begin!)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You ink the area to swim around looking for leftover XP..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (Opponent goes straight for your base..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You splat them, and grab their dropped experience..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (Opponent respawns and starts collecting XP again..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (The timer is closer to running out..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You create an Experience Ball and throw it into their base defense systems..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (You wonder where your Opponent is, but they've already thrown an Experience Ball into yours as well..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay! (**Pearl & Marina** makes some encouraging beats!)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (You are encouraged by this encouraging music, using this determination to your advantage..)")
    await asyncio.sleep(2)
    await turf_battle.edit(content="Ay.. (The battle goes from there..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (The timer is closer to running out..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (6..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (5..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (4..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (3..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (2..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay.. (1..)")
    await asyncio.sleep(1)
    await turf_battle.edit(content="Ay! (Results coming in..!)")
    await asyncio.sleep(1.5)
